#version 460
#include "lib/RayTracingCommons.glsl"

#define MAX_BONES_PER_SKIN 32
struct Skin {
    mat4[MAX_BONES_PER_SKIN] bones;
};
layout (local_size_x = 256) in;

layout(binding = VERTEX_BIND, set = 0) buffer Vertices { Vertex vertices[]; };

void main() {
    uint gID = gl_GlobalInvocationID.x;
    if (gID < vertices.length()) {
//        Vertex v = vin[gID];
//        vout[gID] = v;
    }
}
